version: "3.9"

services:
  postgres:
    image: postgres:16.2
    container_name: foundation_postgres
    command: postgres -c "max_connections=1024"
    environment:
      SERVICE_NAME: "postgres"
      POSTGRES_DB: "foundation"
      POSTGRES_USER: "foundation"
      POSTGRES_PASSWORD: "foundation"
      POSTGRES_SCHEMA: "foundation"
    ports:
      - 5432:5432
    networks:
        - foundation
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

  foundation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foundation
    ports:
      - 8000:8000
    networks:
      - foundation
    depends_on:
      - foundation_postgres
      - foundation_redis

networks:
    foundation:
        driver: bridge
